from apps.ai_platform.constants import (
    OPERATION_WRITE_MORE_TEXT,
    OPERATION_WRITE_NEW_CHAPTER,
    OPERATION_WRITE_NOTE,
    OPERATION_WRITE_STRUCTURE,
)
from apps.ai_platform.registry import BaseAIProviderHandler


class MockProviderHandler(BaseAIProviderHandler):
    def generate(self, *, model_code, prompt, options, credentials, context):
        note_title = context.get('note_title') or 'Untitled note'
        operation_type = options.get('operation_type')

        if operation_type == OPERATION_WRITE_STRUCTURE:
            return {
                'operations': [
                    {
                        'type': 'insert_header',
                        'level': 2,
                        'text': f'Introduction: {note_title}',
                    },
                    {
                        'type': 'insert_header',
                        'level': 2,
                        'text': f'Key ideas for {note_title}',
                    },
                ]
            }

        if operation_type == OPERATION_WRITE_NOTE:
            return {
                'operations': [
                    {
                        'type': 'insert_header',
                        'level': 2,
                        'text': f'Introduction: {note_title}',
                    },
                    {
                        'type': 'insert_text',
                        'html': (
                            '<p>This section was generated by '
                            'Mock provider.</p>'
                        ),
                    },
                    {
                        'type': 'insert_header',
                        'level': 2,
                        'text': f'Practical steps for {note_title}',
                    },
                    {
                        'type': 'insert_text',
                        'html': (
                            '<p>Add practical details and '
                            'examples here.</p>'
                        ),
                    },
                ]
            }

        if operation_type == OPERATION_WRITE_NEW_CHAPTER:
            return {
                'operations': [
                    {
                        'type': 'insert_header',
                        'level': 2,
                        'text': f'New chapter for {note_title}',
                    },
                    {
                        'type': 'insert_text',
                        'html': '<p>This is a newly generated chapter.</p>',
                    },
                ]
            }

        if operation_type == OPERATION_WRITE_MORE_TEXT:
            return {
                'operations': [
                    {
                        'type': 'insert_text',
                        'html': (
                            '<p>Additional generated text '
                            'for current context.</p>'
                        ),
                    }
                ]
            }

        return {'operations': []}
