# Generated by Django 6.0.3 on 2026-03-20 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0009_merge_20260320_1657'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationJob',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('write_structure', 'Write structure'), ('write_note', 'Write note'), ('write_new_chapter', 'Write new chapter'), ('write_more_text', 'Write more text')], max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('source_block_uuid', models.UUIDField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_jobs', to='blog.note')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ai_writing__status_66a1cc_idx'), models.Index(fields=['note', 'created_at'], name='ai_writing__note_id_a3a042_idx'), models.Index(fields=['owner', 'created_at'], name='ai_writing__owner_i_489ce3_idx')],
            },
        ),
    ]
