# Generated by Django 6.0.3 on 2026-03-20 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_merge_20260320_1657'),
        ('ai_writing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'operation_type',
                    models.CharField(
                        choices=[
                            ('write_structure', 'Write structure'),
                            ('write_note', 'Write note'),
                            ('write_new_chapter', 'Write new chapter'),
                            ('write_more_text', 'Write more text'),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    'provider_code',
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    'model_code',
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('running', 'Running'),
                            ('succeeded', 'Succeeded'),
                            ('failed', 'Failed'),
                        ],
                        db_index=True,
                        default='running',
                        max_length=20,
                    ),
                ),
                (
                    'celery_task_id',
                    models.CharField(blank=True, max_length=64),
                ),
                ('request_prompt', models.JSONField(blank=True, default=dict)),
                (
                    'request_options',
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    'request_context',
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    'request_metadata',
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    'response_payload',
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    'normalized_operations',
                    models.JSONField(blank=True, default=list),
                ),
                (
                    'result_metadata',
                    models.JSONField(blank=True, default=dict),
                ),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                (
                    'duration_ms',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='logs',
                        to='ai_writing.aigenerationjob',
                    ),
                ),
                (
                    'note',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ai_generation_logs',
                        to='blog.note',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ai_generation_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['owner', 'created_at'],
                        name='ai_writing__owner_i_91ab06_idx',
                    ),
                    models.Index(
                        fields=['note', 'created_at'],
                        name='ai_writing__note_id_62290f_idx',
                    ),
                    models.Index(
                        fields=['job', 'created_at'],
                        name='ai_writing__job_id_752307_idx',
                    ),
                    models.Index(
                        fields=['status', 'created_at'],
                        name='ai_writing__status_01fead_idx',
                    ),
                ],
            },
        ),
    ]
