# Generated by Django 6.0.3 on 2026-03-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0002_aigenerationlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aigenerationjob',
            options={'ordering': ['-created_at'], 'permissions': [('can_use_ai', 'Can use AI features')]},
        ),
        migrations.RenameIndex(
            model_name='aigenerationlog',
            new_name='ai_writing__owner_i_3466de_idx',
            old_name='ai_writing__owner_i_91ab06_idx',
        ),
        migrations.RenameIndex(
            model_name='aigenerationlog',
            new_name='ai_writing__note_id_ff550a_idx',
            old_name='ai_writing__note_id_62290f_idx',
        ),
        migrations.RenameIndex(
            model_name='aigenerationlog',
            new_name='ai_writing__job_id_3b3943_idx',
            old_name='ai_writing__job_id_752307_idx',
        ),
        migrations.RenameIndex(
            model_name='aigenerationlog',
            new_name='ai_writing__status_7a7900_idx',
            old_name='ai_writing__status_01fead_idx',
        ),
    ]
