# Generated by Django 6.0.2 on 2026-02-18 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_note_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteheader',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='notetextcontent',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='noteheader',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(2, 'H2'), (3, 'H3')], default=2),
        ),
    ]
