# Generated by the assistant to allow blank note titles.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_deduplicate_block_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200, blank=True, default=''),
        ),
    ]
