# Generated by Django 6.0.2 on 2026-02-25 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_add_fields_to_integration'),
        ('integrations', '0003_rename_integrat_code_idx_integration_code_466fa6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integrations', to='integrations.integrationdefinition'),
        ),
    ]
