# Generated by Django 6.0.2 on 2026-03-04 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_integration_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIntegrationDefault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publish_settings', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_integrations', to='blog.blog')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_defaults', to='blog.integration')),
            ],
            options={
                'ordering': ['blog', 'created_at'],
                'indexes': [models.Index(fields=['blog'], name='blog_blogin_blog_id_4dfe83_idx'), models.Index(fields=['integration'], name='blog_blogin_integra_f6dc4b_idx')],
                'unique_together': {('blog', 'integration')},
            },
        ),
    ]
