# Generated by Django 6.0.3 on 2026-03-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_make_note_title_blank'),
        ('blog', '0008_blogintegrationdefault'),
    ]

    operations = [
    ]
