# Generated by Django 6.0.2 on 2026-02-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='integrationdefinition',
            new_name='integration_code_466fa6_idx',
            old_name='integrat_code_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationdefinition',
            new_name='integration_categor_c55779_idx',
            old_name='integrat_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationdefinition',
            new_name='integration_is_acti_0666a3_idx',
            old_name='integrat_active_idx',
        ),
        migrations.RenameIndex(
            model_name='publishtarget',
            new_name='integration_content_3a37ee_idx',
            old_name='ptarget_ct_obj_idx',
        ),
        migrations.RenameIndex(
            model_name='publishtarget',
            new_name='integration_status_037f46_idx',
            old_name='ptarget_status_idx',
        ),
        migrations.RenameIndex(
            model_name='publishtarget',
            new_name='integration_integra_6ab998_idx',
            old_name='ptarget_integ_idx',
        ),
    ]
