# Generated by Django 6.0.3 on 2026-03-20 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('request_timeout_seconds', models.PositiveIntegerField(default=60)),
                ('retry_count', models.PositiveIntegerField(default=2)),
                ('retry_backoff_seconds', models.PositiveIntegerField(default=3)),
                ('max_parallel_tasks', models.PositiveIntegerField(default=4)),
                ('queue_name', models.CharField(default='ai', max_length=64)),
                ('default_temperature', models.FloatField(default=0.7)),
                ('default_max_tokens', models.PositiveIntegerField(default=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('operation_type', models.CharField(choices=[('write_structure', 'Write structure'), ('write_note', 'Write note'), ('write_new_chapter', 'Write new chapter'), ('write_more_text', 'Write more text')], max_length=64)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField()),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.CharField(default='1.0', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['operation_type', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('handler_path', models.CharField(max_length=500)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.CharField(default='1.0', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('base_url', models.URLField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='ai_platform.aiproviderdefinition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider',), name='ai_credential_unique_provider')],
            },
        ),
        migrations.CreateModel(
            name='AIModelDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=200)),
                ('max_context_tokens', models.PositiveIntegerField(default=4096)),
                ('max_output_tokens', models.PositiveIntegerField(default=2048)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_platform.aiproviderdefinition')),
            ],
            options={
                'ordering': ['provider__priority', 'priority', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'code'), name='ai_model_unique_provider_code')],
            },
        ),
    ]
